apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-web
  annotations:
    kubernetes.io/ingress.class: nginx  
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  namespace: uptime-kuma
spec:  
  tls:
    - hosts:
        - uptime.127.0.0.1.nip.io
      secretName: tls-uptime-kuma-web-ingress
