apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: uptime-kuma-web
    namespace: uptime-kuma
    version: v1
images:
- name: louislam/uptime-kuma
  newName: louislam/uptime-kuma
  newTag: 1.17.1-debian
