apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: uptime-kuma-web
    namespace: uptime-kuma
- path: deployment-patch.yml
  target:
    group: apps/v1
    version: v1
    kind: Deployment
    name: uptime-kuma-web
    namespace: uptime-kuma
