kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma-web-pvc
  namespace: uptime-kuma
  labels:
    app: uptime-kuma-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi